var div = document.createElement("div");
var a = document.createElement("p");
a.appendChild(document.createTextNode("Random Stuff"));
a.className = "menu";
var b = document.createElement("p");
b.appendChild(document.createTextNode("More Stuff"));
b.setAttribute("class", "tag");
var c = document.createElement("span");
c.innerHTML = '<p class="name">Some Junk</p><hr/><p>More Junk</p>';
div.appendChild(a);
div.appendChild(b);
div.appendChild(c);
c.firstChild.innerHTML = "Random Junk<br/>";
